-- Suppression des tables si elles existent déjà (ordre inverse des dépendances)
DROP TABLE IF EXISTS FICHIERS;
DROP TABLE IF EXISTS ECHANTILLONS;
DROP TABLE IF EXISTS CAMPAGNE;
DROP TABLE IF EXISTS PLATEFORME;
DROP TABLE IF EXISTS EQUIPEMENT;
DROP TABLE IF EXISTS PERSONNE;
DROP TABLE IF EXISTS HABILITATION;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS LABORATOIRE;


-- Création des tables
CREATE TABLE IF NOT EXISTS LABORATOIRE (
    nomLab VARCHAR(255) PRIMARY KEY,
    adresse VARCHAR(255),
    budget INT
);

CREATE TABLE IF NOT EXISTS LIEU (
    nomL PRIMARY KEY, 
    typeL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS HABILITATION (
    typeHab ENUM('Electrique','Chimique','Biologique','Radioactive')
);

CREATE TABLE IF NOT EXISTS PERSONNE (

);

CREATE TABLE IF NOT EXISTS EQUIPEMENT (

);

CREATE TABLE IF NOT EXISTS PLATEFORME (

);

CREATE TABLE IF NOT EXISTS CAMPAGNE (

);

CREATE TABLE IF NOT EXISTS ECHANTILLONS (

);

CREATE TABLE IF NOT EXISTS FICHIERS (

);

CREATE table if not exists PARTICIPER(

);

Create table if not exists EXPLOITER(

);


